### ISSUE TITLE
unhandled exception (let me know if you need some .esp)

### ISSUE THREAD

**Issue by abitoftaste** [NullCascade/TES3Merge#1]
[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/3244703/TES3Merge.log)

**Comment by NullCascade** [comment]
Can you try with this, and trigger the crash again?
[TES3Merge-Test.zip](https://github.com/NullCascade/TES3Merge/files/3244910/TES3Merge-Test.zip)

**Comment by NullCascade** [comment]
Fixed in e09becfa36ad375334432f3c8a8ae791b7d0bac0
