### ISSUE TITLE
Merging factions causes crashes in game.

### ISSUE THREAD

**Issue by Virnetch** [NullCascade/TES3Merge#10]
[D.zip](https://github.com/NullCascade/TES3Merge/files/3268727/D.zip)

**Comment by NullCascade** [comment]
Give this build a try. It prevents certain faction data from merging, but should not produce invalid results. More fine-grain merging will need to be added back in later.

[TES3Merge 0.6-prerelease.zip](https://github.com/NullCascade/TES3Merge/files/3272990/TES3Merge.zip)

**Comment by Virnetch** [comment]
It's still crashing with that one.
