### ISSUE TITLE
Why Mono?

### ISSUE THREAD

**Issue by Svetomechc** [NullCascade/TES3Merge#11]
Just a little curious why you picked Mono and not .NET Core. Was there a specific reason?

**Comment by benjaminwinger** [comment]
Assuming you're referring to what I said in #7, I tried both mono and the dotnet core sdk, but dotnet core gave an error. Mono on the other hand worked fine (at least, once I figured out how the ini-parser dependency needed to be configured). It's certainly possible that dotnet core can also work, but I didn't want spend too much time fiddling with it.
