### ISSUE TITLE
Serious error

### ISSUE THREAD

**Issue by dagothragnor** [NullCascade/TES3Merge#12]
[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/4114667/TES3Merge.log)

**Comment by dagothragnor** [comment]
it happens

**Comment by Orrange06** [comment]
[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/4119320/TES3Merge.log)

Same issue here

**Comment by OkabeRintaro** [comment]
I have what appears to be the same issue
[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/4172836/TES3Merge.log)

**Comment by mdsouthworth1** [comment]
Similar issue
[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/4178485/TES3Merge.log)

**Comment by Pop000100** [comment]
Same error message
[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/4189846/TES3Merge.log)

**Comment by NullCascade** [comment]
This should be fixed in v0.8. If not, please post an updated TES3Merge.log.
