### ISSUE TITLE
a serious error has occured v.0.6.1

### ISSUE THREAD

**Issue by moeeom123** [NullCascade/TES3Merge#14]
had error with version 0.6.1 the .log belongs to that. with 0.5. it ran without error

[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/4411205/TES3Merge.log)

**Comment by raveren** [comment]
I think mine's similar - errors out when merging Dagoths:

[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/4770468/TES3Merge.log)

**Comment by coracleboat** [comment]
Also having this problem hitting me right after it merges some Dagoths.

[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/4984117/TES3Merge.log)

**Comment by NullCascade** [comment]
This should be fixed in v0.8. If not, please post an updated TES3Merge.log.
