### ISSUE TITLE
Serious Issue has Occured 0.6.1

### ISSUE THREAD

**Issue by Suilean** [NullCascade/TES3Merge#15]
[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/5106801/TES3Merge.log)

I'm seeing references to D:\Projects\ in the unhandled exception, which isn't a folder I have on my PC. TES3Merge is in my game directory, which is on my C:.

**Comment by NullCascade** [comment]
This should be fixed in v0.8. If not, please post an updated TES3Merge.log.
