### ISSUE TITLE
NPCO - Item records from multiple mods not merged

### ISSUE THREAD

**Issue by Toriansel** [NullCascade/TES3Merge#18]
When several mods add an NPCO record to an NPC the newly added items are not merged into the final record of the merge mod. An example would be the following:

To the NPC bm_roguenecro3 record the following three mods add the following four objects:

* Hold It - aa_necro_hold and aa_necro_hold_l
* LootableSpellbooks - random_spellbook
* Equipment Variants - aa_silver_staff (removes silver staff)

Whichever mods is last in the load order gets it's added item added to the NPC's inventory in the merge mod. I would suggest all four new items should have been added (and the silver staff removed). There might be a case I'm not thinking of where this is correct behavior.

**Comment by NullCascade** [comment]
I want to do this with inventories, leveled lists, and AI packages. Just haven't gotten around to it yet.

**Comment by Toriansel** [comment]
Ya, that makes sense. This specific set of inventories is basically the same problem as level lists for sure.

Anyway, thanks for the tool. It works well.

**Comment by rfuzzo** [comment]
this is implemented in #27 as a commandline option `-i` (inclusive list merge)
