### ISSUE TITLE
Issues were found with your .ini file

### ISSUE THREAD

**Issue by Kudix** [NullCascade/TES3Merge#2]
Hi

just droped your app into my Morrowind folder and doubleclicked the .exe file. 
[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/3245084/TES3Merge.log)

**Comment by NullCascade** [comment]
It's showing you that you have invalid entries in your Morrowind.ini file. In this case, you have at least a duplicate Texture 3 in your blood section.

**Comment by NullCascade** [comment]
You can try this pre-release version of TES3Merge, which will try to be more forgiving with your INI file. Let me know if it helps!

[TES3Merge.zip](https://github.com/NullCascade/TES3Merge/files/3245257/TES3Merge.zip)
