### ISSUE TITLE
TES3Merge serious error?

### ISSUE THREAD

**Issue by TheSeeker27** [NullCascade/TES3Merge#22]
[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/6324275/TES3Merge.log)

**Comment by TheSeeker27** [comment]
So apparently I was using both MCA names 8.1 and MCA 8 by abot. I disabled MCA names 8.1, which solved the issue.

**Comment by NullCascade** [comment]
You're also using a very old version of TES3Merge. 0.8 shouldn't give you the issues 0.6 did.
