### ISSUE TITLE
TES3Merge error

### ISSUE THREAD

**Issue by PublicolaMinor** [NullCascade/TES3Merge#24]
Here's my TES3Merge.log file; I have no idea what the error message means. "Object reference not set to an instance of an object." for the NPC 'fara'?  Let me know what you can make of it. I'd previously used all three mods referenced (more barter gold, BCOM, and hold it) in my previous install without issues, so let me know what you find.
[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/7612776/TES3Merge.log)
.

**Comment by PublicolaMinor** [comment]
Never mind. Looked through each of the last few error messages, and found the instructions provided by sulez745:
> Open this plugin in TESAME, click Mods>Autoclean>check NPCs only>Start. There should be 13 "illegal items". Click "remove all". Save plugin and then you should run TES3Merge without errors.
I followed the instructions and TES3Merge was able to run without a problem. No idea why RandomPal's creatures expansion would cause this issue.

**Comment by PublicolaMinor** [comment]
I posted a comment with the error report to RandomPal's [Vanilla-Friendly Creature Expansion page](https://www.nexusmods.com/morrowind/mods/48818), asking him to take a look. Here's his response:

> This is more an issue with tes3merge going crazy sometimes when merging certain types of records rather than an issue with the mod.
> I never used the autoclean function of tesame but I tried it to see what it would do. As I suspected, it simply removed some edits.
>When it says "potentially illegal", it's because the software is simply checking if the ID of the NPC is the same as a vanilla NPC. It's not a new ID and so it's marking it as possible dirty edit.
> Tes3cmd is smarter in that as it checks if there's something being changed about that particular item (an NPC, in this case).
>Cleaning the records of course works as tes3merge just doesn't have to merge the problematic records now, but you're removing intended edits.
>In this case, the records being removed are those relative to the various dreamers. I gave them obisidian weapons (https://www.nexusmods.com/morrowind/mods/47200) but if you clean/cut the records then you're cutting this feature out of the mod, essentially.

Having 'merged objects.esp' working is more important than having an extra feature from this mod, so I'll continue using the edited version without obsidian weapons, but can you take a look at TES3Merge to see if there's a way to get it to work with RandomPal's changes? Thanks!

**Comment by NullCascade** [comment]
Give [this build](https://github.com/NullCascade/TES3Merge/files/7782970/tes3merge.zip) a try, let me know if you have any further issues.
