### ISSUE TITLE
TES3Merge v0.4 Serious Error has Occurred

### ISSUE THREAD

**Issue by OkabeRintaro** [NullCascade/TES3Merge#4]
[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/3249022/TES3Merge.log)

**Comment by NullCascade** [comment]
Hi OkabeRintaro, can you give this build a try?
[TES3Merge.zip](https://github.com/NullCascade/TES3Merge/files/3250044/TES3Merge.zip)

**Comment by OkabeRintaro** [comment]
This build still gives me a serious error, here's the log.
[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/3250146/TES3Merge.log)

**Comment by NullCascade** [comment]
Give this version a try, and let me know if it fixes it:
[TES3Merge.zip](https://github.com/NullCascade/TES3Merge/files/3252317/TES3Merge.zip)

**Comment by OkabeRintaro** [comment]
That version, as well as version v0.5 that you just released, fixed the issue and now the merge is working as normal.

**Comment by NullCascade** [comment]
Great, thanks for testing.
