### ISSUE TITLE
Unable to locate target '' in EscortPack init.

### ISSUE THREAD

**Issue by SumSineRegno** [NullCascade/TES3Merge#5]
So while loading up Morrowind with a merged objects esp from this tool I got this peculiar error. Not sure if it is fatal, but here is both logs so that you might be able to see what is going on. Using the current version on Nexus, might revert to an older version to test.

[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/3250178/TES3Merge.log)
[Warnings.txt](https://github.com/NullCascade/TES3Merge/files/3250180/Warnings.txt)

**Comment by SumSineRegno** [comment]
Yep still is there when reverting to V .3 Going to test if it is any particular mod not playing nicely.

[TES3Merge.log](https://github.com/NullCascade/TES3Merge/files/3250249/TES3Merge.log)

**Comment by NullCascade** [comment]
Give this version a try, and let me know if it fixes it:
[TES3Merge.zip](https://github.com/NullCascade/TES3Merge/files/3252317/TES3Merge.zip)

**Comment by SumSineRegno** [comment]
Sorry, I got up late. Does you still need me to test the fix now that v0.5 is out? Or would you like me to close the issue?

**Comment by SumSineRegno** [comment]
Appears to be fixed in v0.5.
